cc_library(name = 'jansson',
          srcs = glob(["*.cc", "*.c"]),
          hdrs = glob(["*.h"]),
          deps = [
            "//base/common",
          ],
          visibility = ["//visibility:public"],
        )
