cc_library(name = "util",
           srcs = glob(["*.cc"]),
           hdrs = glob(["*.h"]),
           deps = [
             "//base/common",
             "//base/hash",
             "//base/jansson",
           ],
           visibility = ["//visibility:public"],
           )
