cc_library(name = "random",
           srcs = glob(["*.cc"]),
           hdrs = glob(["*.h"]),
           deps = [
              "@abseil-cpp//absl/random:random",
              "//base/common",
           ],
           visibility = ["//visibility:public"],
           )
