
cc_library(name = "testing",
        srcs = ["test_main.cc",],
        hdrs = ["gtest.h",],
        deps = [
          "//base/common",
          "@googletest//:gtest",
          "@googletest//:gtest_main",
        ],
        visibility = ["//visibility:public"],
        )
