cc_library(name = "thread",
           srcs = glob(["*.cc"]),
           hdrs = glob(["*.h"]),
           deps = [
              "//base/common",
              "@abseil-cpp//absl/synchronization",
           ],
           visibility = ["//visibility:public"],
           )
